/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "BaoStudy",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "script",
      {
        "src": "/js/bodyclick.js"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "https://www.zpzpup.com/assets/image/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "积跬步以至千里",
        "tagline": "致敬每一个正在努力学习的你",
        "heroTextStyle": {
          "color": "#fff"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-57661bda",
      "path": "/"
    },
    {
      "title": "222",
      "frontmatter": {
        "sidebarDepth": 0
      },
      "regularPath": "/blogs/java/one.html",
      "relativePath": "blogs/java/one.md",
      "key": "v-48c0e65f",
      "path": "/blogs/java/one.html"
    },
    {
      "title": "springboot中redis缓存",
      "frontmatter": {},
      "regularPath": "/blogs/java/two.html",
      "relativePath": "blogs/java/two.md",
      "key": "v-775f88da",
      "path": "/blogs/java/two.html",
      "headers": [
        {
          "level": 3,
          "title": "依赖注入",
          "slug": "依赖注入"
        },
        {
          "level": 3,
          "title": "配置redis序列化",
          "slug": "配置redis序列化"
        },
        {
          "level": 3,
          "title": "@Cacheable、@CachePut、@CacheEvict三个核心注解的使用",
          "slug": "cacheable、-cacheput、-cacheevict三个核心注解的使用"
        }
      ]
    },
    {
      "title": "Redis 应用问题解决",
      "frontmatter": {
        "title": "Redis 应用问题解决",
        "date": "2022-3-5",
        "sidebar": "auto",
        "categories": [
          "系列教程"
        ],
        "tags": [
          "Redis"
        ]
      },
      "regularPath": "/blogs/web/one.html",
      "relativePath": "blogs/web/one.md",
      "key": "v-117ea047",
      "path": "/blogs/web/one.html",
      "headers": [
        {
          "level": 2,
          "title": "Redis 应用问题解决",
          "slug": "redis-应用问题解决"
        },
        {
          "level": 3,
          "title": "1. 缓存穿透",
          "slug": "_1-缓存穿透"
        },
        {
          "level": 3,
          "title": "2. 缓存击穿",
          "slug": "_2-缓存击穿"
        },
        {
          "level": 3,
          "title": "3. 缓存雪崩",
          "slug": "_3-缓存雪崩"
        }
      ]
    },
    {
      "title": "springboot中redis缓存",
      "frontmatter": {},
      "regularPath": "/blogs/web/two.html",
      "relativePath": "blogs/web/two.md",
      "key": "v-5cfc8f87",
      "path": "/blogs/web/two.html",
      "headers": [
        {
          "level": 3,
          "title": "依赖注入",
          "slug": "依赖注入"
        },
        {
          "level": 3,
          "title": "配置redis序列化",
          "slug": "配置redis序列化"
        },
        {
          "level": 3,
          "title": "@Cacheable、@CachePut、@CacheEvict三个核心注解的使用",
          "slug": "cacheable、-cacheput、-cacheevict三个核心注解的使用"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Redis Tags"
      },
      "regularPath": "/tag/Redis/",
      "key": "v-cd4f2d44",
      "path": "/tag/Redis/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "系列教程 Categories"
      },
      "regularPath": "/categories/%E7%B3%BB%E5%88%97%E6%95%99%E7%A8%8B/",
      "key": "v-56e37998",
      "path": "/categories/系列教程/"
    }
  ],
  "themeConfig": {
    "noFoundPageByTencent": false,
    "modePicker": false,
    "lastUpdated": "Last Updated",
    "author": "阿元搞全栈",
    "type": "blog",
    "authorAvatar": "/img/avatar.png",
    "record": "BaoStudy.com — All Rights Reserved.",
    "cyberSecurityRecord": "粤ICP备2021021642号",
    "cyberSecurityLink": "https://beian.miit.gov.cn",
    "startYear": "2021",
    "subSidebar": "auto",
    "smoothScroll": true,
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "博客",
        "link": "/"
      },
      {
        "text": "教程",
        "icon": "reco-category",
        "items": [
          {
            "text": "Web",
            "link": "/blogs/web/"
          }
        ]
      }
    ],
    "sidebar": {
      "/blogs/java/": [
        {
          "title": "JAVA",
          "collapsable": false,
          "children": [
            "one",
            "two"
          ]
        }
      ],
      "/blogs/web/": [
        {
          "title": "WEB",
          "collapsable": false,
          "children": [
            "one",
            "two"
          ]
        }
      ]
    }
  }
}