/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Redis": {
      "key": "Redis",
      "scope": "tags",
      "path": "/tag/Redis/",
      "pageKeys": [
        "v-117ea047"
      ]
    }
  },
  "categories": {
    "系列教程": {
      "key": "系列教程",
      "scope": "categories",
      "path": "/categories/系列教程/",
      "pageKeys": [
        "v-117ea047"
      ]
    }
  },
  "timeline": {}
}