/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Redis",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Redis/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "系列教程",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/系列教程/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]